# This workflow is triggered on push events to the 'dev' branch
on:
  push:
    branches:
      - dev

name: Create Pull Request to Test Branch

jobs:

  create-pull-request:
    name: Create Pull Request to Test Branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "dev"
        destination_branch: "test"
        pr_title: "Pulling changes from dev to test"
        pr_body: "Automatically created pull request to merge changes from dev to test"
        github_token: ${{ secrets.GITHUB_TOKEN }}